### PR TITLE
Fix slug validation behavior

### LINKED ISSUE #558: Slug validation should deny numbers-only
@teury wrote:

> if you put a single number in the slug creates an error

...meaning that the form accepts '1' as a slug, but the url pattern doesn't match. The point is that a number is interpreted as an Article ID and not a slug path, so any pure number shouldn't be accepted as a slug.

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes #558 and #554

### CODE REVIEW

File: wiki/static/wiki/js/urlify.js [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+        */
+        var removelist = [];
+
+        var r = new RegExp('\\b(' + removelist.join('|') + ')\\b', 'gi');
+        s = s.replace(r, '');
+        // if downcode doesn't hit, the char will be stripped here
+        if (allowUnicode) {
+            // Keep Unicode letters including both lowercase and uppercase
+            // characters, whitespace, and dash; remove other characters.
+            s = XRegExp.replace(s, XRegExp('[^-_\\p{L}\\p{N}\\s]', 'g'), '');
```
Comment (nschneid) [inline wiki/static/wiki/js/urlify.js]: Where is `XRegExp` defined? I'm trying to use this code in a custom form and am getting an error.

Comment (nschneid) [reply wiki/static/wiki/js/urlify.js]: Oh I see, I need to include the script from /static/admin/js/vendor/xregexp/xregexp.min.js to use `allowUnicode=true`.
